From python:3.11-slim

WORKDIR /hello_world

COPY hello_world/requirements.txt /hello_world/requirements.txt
RUN pip install --no-cache-dir -r /hello_world/requirements.txt

COPY hello_world /hello_world

EXPOSE 8000

CMD [ "python","app.py" ]
