apiVersion: v1
kind : Deployment
metadata: 
    name: hello-world
spec:
    replicas: 2
    selector:
        matchLabels:
            app: hello-world
    template:
        metadata:
            labels:
                app: hello-world
        spec:
            container:
            - name: hello-world
              image: "{{.values.image.repository}}:{{.values.image.tag}}"
              port:
              - containerPort: 8000